name: PYPI Release

on: 
 push:
  branches:
    - main
  tags:
    - 'v*'

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Source Cargo Environment
        run: source $HOME/.cargo/env

      - name: Build with UV
        run: uvx --from build pyproject-build --installer uv
      
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1