name: PYPI Release

on: 
 push:
  tags:
    - 'v*'

jobs:
  pypi_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Source Cargo Environment
        run: source $HOME/.cargo/env

      - name: Build with UV
        run: uvx --from build pyproject-build --installer uv
      
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN_TEMP }}
          packages_dir: ./dist/
