name: PYPI Release

on: [push, pull_request]

jobs:
  setup_uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Source Cargo Environment
        run: source $HOME/.cargo/env

      - name: Build with UV
        run: uvx --from build pyproject-build --installer uv
      
      # - name: Upload to PyPi
        # run: uvx twine upload dist/*